### ISSUE TITLE
Аддикт курения(может и не только) не работает

### ISSUE THREAD

**Issue by joctopus** [top4secret5drvn/derven_station_13#6]

**Comment by joctopus** [comment]
![image](https://cloud.githubusercontent.com/assets/14141649/24463292/09f1d62c-14af-11e7-93b7-c1b2c102d8b4.png)

**Comment by PlinHost** [comment]
Ласт тайм я играл аддикты отключить в меню создания персонажа было нельзя.

**Comment by joctopus** [comment]
@PlinHost А надо ли их отключать? Может, как на Луфике?:^)

**Comment by PlinHost** [comment]
Они пиздец будут мешать строительству. Мазохисты пусть себе ставят, но не всех же заставлять.

**Comment by top4secret5drvn** [comment]
Аддикты сильно нерфануты.
